### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by LNSD** [jenzz/gradle-android-buildconstants-plugin#3]
Hi @jenzz ,

I've added your plugin to my project, but i'm having the following error:

```
Error:(33, 0) Cause: com/jenzz/buildconstants/BuildConstantsPlugin : Unsupported major.minor version 52.0
```

You can check the commit where I've added this plugin to the project: [Commit (Citikey/citikey-android  - feature/constants)](https://github.com/Citikey/citikey-android/commit/2d02783714d784347c1e87548d84630393ef70a6)

And here you have my `./gradlew` version info:

```
$ ./gradlew -v

------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Windows 10 10.0 amd64
```

Regards,
Llorens

PS: I've  always been creating my two constant files manually. If this plugin work, **it would be a great time saver.** :grin:

**Comment by LNSD** [comment]
Dear @jenzz,

I've found the solution to the problem. I was building the project with `jdk1.7.0_79`. After changing in the project settings the JVM with `jdk1.8.0_92` version, it is working. :tada:

**Comment by jenzz** [comment]
Yeah this message usually pops up when there is a mismatch between the Java version you use at **compile time** vs. **run time**.
I'm glad you found the solution.

What I usually do is make sure that my `JAVA_HOME` constants are all properly set up:

``` java
export JAVA7_HOME=`/usr/libexec/java_home -v 1.7`
export JAVA8_HOME=`/usr/libexec/java_home -v 1.8`
export JAVA_HOME=$JAVA8_HOME
```

...and then double-check that the correct JDK is used in the module / project settings of AS.
